# Basar el contenedor en la ultima imagen de Ubuntu
FROM ubuntu:latest

# Author
 LABEL mantainer="Erick Calderin"

 # Upgrage packages to latest version
 RUN apt-get update && apt-get upgrade -y

 # Install necessary applications
 RUN apt-get install git -y